### ISSUE TITLE
Can‘t find any file I have just create by "orgrr-find"

### ISSUE THREAD

**Issue by Dasein1998** [rtrppl/orgrr#12]
I install [orgrr](https://github.com/rtrppl/orgrr) by straight as you write in readme.(In win10)
And I have set (setq org-directory "~/org-roam/").
Orgrr can create file in ~/org-roam/, but cannot find any note I have ,or I have just created.

**Comment by rtrppl** [comment]
Hi there & thanks for the interest. 

There might be a few things at play here:

1. I  have no experience with Emacs in Win10, but the structure of paths is different there, right? In Linux and macOS we use /, in Windows it is \, right? If you don't set a org-directory, Orgmode sets ~/org (or the equivalent in Win). You might want to try that. Edit: Reading this [H.3 File Names on MS-Windows](https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-Files.html), this may not the issue at hand.
2. Did you save your new notes (M-x save-buffer)? All notes have to be saved, to appear somewhere. Depending on your setup and if that directory is new, you might have to confirm to create the directory.   

Hope this helps.

**Comment by Dasein1998** [comment]
Thanks for reply. 
I try to use "~/org-roam/","~\org-roam/",even "c/user/username/org-roam/" as  org-directory, orgrr can create file normally. But can't find the note I just created and saved. 
And I try to debug it, found that the "~/.orgrr-container-list" contain just one line :" {"main":"~/org-roam/"}".
But without any hash of my notes. 
I guess it may cause "orgrr-find" can't find anything in ~/org-roam/?
And `rg -i --sort modified "^#+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*) "C:/Users/username/org-roam/" -g *.org` work well in powershell, but not in cmd.
So I try a minium code in scratch:
```lisp
(message (shell-command-to-string (concat "rg -i --sort modified \"^\\#\\+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*)\" '" (expand-file-name org-directory) "' -g \"*.org\"")))
(setq org-directory "~/org-roam")
```
After a dozen times trying, I found the problem is the ` ' ' ` in  ` '" (expand-file-name org-directory) "'`.
so I delete the ` ' ' `  in line 216 of orgrr.el.
```lisp
(shell-command-to-string (concat "rg -i --sort modified \"^\\#\\+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*)\" " (expand-file-name org-directory) " -g \"*.org\""))
```
And the orgrr-find work well now. 
Maybe it just work on win10? I dont have any pc with macos or linux for verification.

**Comment by Dasein1998** [comment]
Thanks for reply. 
I try to use "~/org-roam/","~\org-roam/",even "c/user/username/org-roam/" as  org-directory, orgrr can create file normally. But can't find the note I just created and saved. 
And I try to debug it, found that the "~/.orgrr-container-list" contain just one line :" {"main":"~/org-roam/"}".
But without any hash of my notes. 
I guess it may cause "orgrr-find" can't find anything in ~/org-roam/?
And `rg -i --sort modified "^#+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*) "C:/Users/username/org-roam/" -g *.org` work well in powershell, but not in cmd.
So I try a minium code in scratch:
```lisp
(message (shell-command-to-string (concat "rg -i --sort modified \"^\\#\\+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*)\" '" (expand-file-name org-directory) "' -g \"*.org\"")))
(setq org-directory "~/org-roam")
```
After a dozen times trying, I found the problem is the ` ' ' ` in  ` '" (expand-file-name org-directory) "'`.
so I delete the ` ' ' `  in line 216 of orgrr.el.
```lisp
(shell-command-to-string (concat "rg -i --sort modified \"^\\#\\+(title:.*)|(roam_alias.*)|(roam_tags.*)|(zettel:.*)\" " (expand-file-name org-directory) " -g \"*.org\""))
```
And the orgrr-find work well now. 
Maybe it just work on win10? I dont have any pc with macos or linux for verification.

**Comment by rtrppl** [comment]
Thanks for exploring this a bit more. If `'` is the issue, this must be changed in many more locations. I never encountered this on Mac or Linux (and I don't have a Win machine to test :). I have written a fix for this and it should be ready in a few minutes.
