### ISSUE TITLE
Feature request: collect zettelkasten parents and children of the current note for showing its related notes

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/orgrr#14]
Hello!  After using logseq, org-roam, and denote (in that order), I started using orgrr for my daily note taking.  I am simply amazed by how simplistic orgrr is yet how powerful and flexible.  Producing backlinks, links, and related notes via ripgrep (and not relying on database stuff) is simply great.  Also, orgrr has been the first personal knowledge management tool that got me started with using luhmann sequences in my notes.

So, I noticed after a while using orgrr that it doesn't include the luhmann-connectedness for its `orgrr-show-related-notes` function.  Would you consider also adding that?  In my case, I have many files which do not link to others nor are linked from others, BUT, are in a luhmann sequence, such as 4a1.  So, it would be cool to collect and show this note's luhmann parents and children (such as, 4a and possible 4a1a,4a1b,4a1c,...,) in the buffer of its "related notes".

**Comment by k4r4b3y** [comment]
Perhaps this can be done by appending (or prepending) the `sequence for *4a1*` buffer to the "related notes" buffer that gets created by `orgrr-show-related-notes` function.

**Comment by rtrppl** [comment]
Hi! Thanks for the kind words, glad you like orgrr. 

That is an interesting idea - but the new merged buffer for `orgrr-show-related-notes` and `orgrr-show-sequence` might be a bit long and therefore unwieldy. It would be rather easy to implement if you are primarily interested in the "children" (4a1a, 4a1b etc..). I will look into this.

**Comment by k4r4b3y** [comment]
>might be a bit long and therefore unwieldy.

Yes, it might be.  However, I think hitting `TAB` on org mode headings for "sequence" and "related notes" would roll down up/down, and hide the portions of the buffer, if the user desires to do so.

>It would be rather easy to implement if you are primarily interested in the "children" (4a1a, 4a1b etc..).

Good to hear.  However, would you also add the one level up parent of luhmann sequence also, perhaps?  I think seeing what files were the parent of the current note would be useful in re-capturing the thought process that went into that file.

**Comment by rtrppl** [comment]
![orgrr-show-super-related](https://github.com/user-attachments/assets/4282c2d0-db21-4d80-92bc-93e84b8be0ae)

If you want to play around with this function `orgrr-show-super-related`, you'll find an early draft in the branch "orgrr-super-related". This is a Frankenstein-version of both functions hacked together. Adding the reference to the parent note will take more time.

**Comment by rtrppl** [comment]
![orgrr-show-super-related with parent](https://github.com/user-attachments/assets/3eb3a587-b1e7-4bf1-ad22-1a70be337226)

And now with reference to the parent zettel. Does this match your intended feature request?

**Comment by k4r4b3y** [comment]
Hey this is exactly what I had in mind! Thanks for implementing this. I will try the development branch out ASAP.

**Comment by k4r4b3y** [comment]
Just tested it quickly with my small orgrr number of notes.  It is working well.

**Comment by rtrppl** [comment]
Great & thanks for the feedback. The final version might be closer to this:

![orgrr-show-multiverse](https://github.com/user-attachments/assets/31747f85-2213-4966-985b-a88e4f3c8518)

I have switched around `orgrr-show-related-notes` and `orgrr-show-sequence` for two reasons. First, `orgrr-show-sequence` tends to be shorter. And second, pressing "o" now directly takes you to the parent note, which I often want to do. 

I also changed the name of the function (now `orgrr-show-multiverse`).

**Comment by k4r4b3y** [comment]
> I have switched around `orgrr-show-related-notes` and `orgrr-show-sequence` for two reasons. First, `orgrr-show-sequence` tends to be shorter. 

Yes, makes sense.

> And second, pressing "o" now directly takes you to the parent note, which I often want to do.

Nice!

> I also changed the name of the function (now `orgrr-show-multiverse`).

Cool.  Can't wait to have these on the main branch.

**Comment by rtrppl** [comment]
0.9.15 with orgrr-show-multiverse has moved to main. :)
