### ISSUE TITLE
Add clarification on the function of #+roam_tags

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/orgrr#17]
I tried adding #+roam_tags to a few of my orgrr notes, however, when I take a look at the `orgrr-show-multiverse` I don't see it showing the relation of these notes with same tags.

I never used org-roam-v1, so, what does #+roam_tags allow its users to do?

**Comment by rtrppl** [comment]
Tags are limited to orgrr-find and orgrr-insert. I use them only to add meta-data to notes (i.e. the creation date or type of content, if it is a publication). However, there is one big exception to this rule and that is the tag "orgrr-project". If you add this tag, a number of additional functions become available (as described in the documentation). 

Btw. if you use Mastodon and have additional questions about orgrr you can also find me there at @laotang@mastodon.social

**Comment by k4r4b3y** [comment]
Not to be rude, but I am not on fediverse.  May I reach you via email?  I would like to understand better the `orgrr-project` feature, too.

**Comment by rtrppl** [comment]
No offence taken. There are a lot of Emacs users on Mastodon and it is a good place for a public discussion on features. But GitHub is fine, too. I would prefer to keep it here, just in case somebody has similar questions.

**Comment by rtrppl** [comment]
orgrr-project combines several ideas. Adding the tag to a note unlocks two main functions: `orgrr-open-project` and 'orgrr-add-to-project`. The first one allows you to open that note from any container. Handy, if you have several main notes you are working on. The second one allows you to add the paragraph / backlink at point to any note with the orgrr-project tag (again, from all containers).

**Comment by k4r4b3y** [comment]
I am trying to understand what extra functionality `orgrr-*-project` commands bring.  I think I can achieve your examples by simple `orgrr-insert` command, and then taking a look at the note's `orgrr-show-multiverse` command buffer?

One thing that the `*-project` commands can be useful seems to be quickly putting a pointer to a concept, from your notes in your container.  For example, you can keep track of paragraphs that might be related to some concept, such as "Finding a new job", or "Getting a dog" -- but even then the `*-project` commands seem like a quick way to insert file links.

I also don't understand your documentation's example of using the `*-project` commands on the `*Show relations*` buffer of a note; what would that be useful for?

**Comment by rtrppl** [comment]
The orgrr-project commands allow a note to become a staging ground for a larger document. To give you an example: in my teaching career I prepared new courses almost every term. The first stage of this usually involves collecting all information on a topic and related issues in one document. 

The process of collecting these snippets of information from my notes is what you see here:

![Bildschirmfoto 2024-12-16 um 14 30 29](https://github.com/user-attachments/assets/5c04c80f-6445-4a9f-9720-3428101c6fc2)

On the left is the original note with some information that I would like to add to my "brain-storming" document. So I move my cursor to the paragraph in question and invoke `orgrr-add-to-project`. Now the paragraph is added to my selected orgrr-project.

Sometimes the interesting information is in one of the snippets in the backlink results buffer. Accordingly, I move my cursor to the snippet in question and also invoke `orgrr-add-to-project`. This is what you see here:

![Bildschirmfoto 2024-12-16 um 14 31 27](https://github.com/user-attachments/assets/0b011217-3c72-476d-a9e3-0a0000579073)

This works across containers. The quicknote in the example above is in a different container than these two notes (in effect I don't have just 1 but 17 different Zettelkasten). 

Another example: I have directory with several hundred "org-ified" websites (see also [website2org](https://github.com/rtrppl/website2org)). `orgrr-add-to-project` allows me to easily add a paragraph (with a source and working links) from a newspaper article to my staging document.

![Bildschirmfoto 2024-12-16 um 14 55 54](https://github.com/user-attachments/assets/d4e82d80-73dd-4832-bd60-cf54ff9d3156)

I could also use `orgrr-insert` but then would lose the additional context.
