### ISSUE TITLE
Feature request: allow orgrr-add-to-project to pass the region to the project file

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/orgrr#18]
Currently, `orgrr-add-to-project` function seems to pass only the current line (**those without a hard line break**) to the project file.

However, in emacs, I always have my notes formatted with `M-q` (`org-fill-paragraph`) applied.  That is, my paragpraphs do not exceed 70 char width and 71st char gets moved to the next line.

In these cases, `orgrr-add-to-project` only adds the line up to the line break to the project file.

I would like to be able to activate a region with my cursor in one of my orgrr files, and get the `orgrr-add-to-project` function pass the text highlighted by the active region to the orgrr project file.

**Comment by rtrppl** [comment]
> However, in emacs, I always have my notes formatted with `M-q` (`org-fill-paragraph`) applied. That is, my paragpraphs do not exceed 70 char width and 71st char gets moved to the next line.

So this does add a manual line break after 70 characters, right? Honest question: Why would you ever want to do that?  :) If you don't want to resize your window you could use something like `Olivetti-mode`. Having manual line-breaks at random places within a paragraph is a recipe for disasters for any note-taking system. `orgrr-show-backlinks`, for example, uses just one line of `rg` context.  

> I would like to be able to activate a region with my cursor in one of my orgrr files, and get the `orgrr-add-to-project` function pass the text highlighted by the active region to the orgrr project file.

Will look into this if I have some more time.

**Comment by rtrppl** [comment]
The feature is in 0.9.17 (it was just four lines of code). However, you still might want to reconsider adding random line-breaks into paragraphs.

**Comment by k4r4b3y** [comment]
> Honest question: Why would you ever want to do that? :)

It makes reading my notes easier, my eyes do not have to travers a long horizontal distance.  In addition to that, emacs' other facilities (info pages, etc) work with that 70 char rule.  mu4e, etc. work the best with that 70 char rule.   Lots of stuff like this in emacs. 

> Having manual line-breaks at random places within a paragraph is a recipe for disasters for any note-taking system. 

This hasn't been so my experience so far, neither with orgrr, nor with org-roam nor denote.  Applying `M-q` doesn't break a thing (except the topic of this issue thread). 

> orgrr-show-backlinks, for example, uses just one line of rg context.

I didn't notice this as I was only using `orgrr-show-multiverse` to check for the "backlinks".  I will take  look at the `orgrr-show-backlinks` command and see if my paragraph structure is bad for that.

> The feature is in 0.9.17 (it was just four lines of code).

Thanks, I will test it.

**Comment by k4r4b3y** [comment]
> Having manual line-breaks at random places within a paragraph is a recipe for disasters for any note-taking system. orgrr-show-backlinks, for example, uses just one line of rg context.

Alright, I think I notice this with my notes now:

![ss](https://github.com/user-attachments/assets/dc70d1cc-c155-4736-bfa2-f92138c25f73)

The backlinks indeed only adds the context up to the first 71st char line break.

----

Perhaps, would you consider extending this addition of the context up to the next **dot and then double spaces?**  This is how I put the sentence ending dot and the whitespaces.

OR, would you consider this addition of the backlinks context up to the next **double newline characters?**   This is also how I separate my paragraphs (just as in here, markdown, or in the reddit, the user uses double newlines to separate paragraphs).

**Comment by rtrppl** [comment]
> > Honest question: Why would you ever want to do that? :)
> 
> It makes reading my notes easier, my eyes do not have to travers a long horizontal distance. In addition to that, emacs' other facilities (info pages, etc) work with that 70 char rule. mu4e, etc. work the best with that 70 char rule. Lots of stuff like this in emacs.

In part I was only kidding. This is Emacs and you can do whatever you want. And I completely agree with the intention to limit the line to somewhere between 70-80 characters shown. This is one of the many reasons I usually use Emacs with one frame split into two windows - or use olivetti-mode for mu4e etc. 

But there is a price you pay by doing so. Parsing line breaks is not as straight forward as it may seem. In website2org the most frustrating aspect are not the several MB of javascript etc that commercial platforms add but random line breaks added by people who write their HTML code themselves. Sometimes these line breaks are important (poems, code), most of the time they are not. 


> 
> > Having manual line-breaks at random places within a paragraph is a recipe for disasters for any note-taking system.
> 
> This hasn't been so my experience so far, neither with orgrr, nor with org-roam nor denote. Applying `M-q` doesn't break a thing (except the topic of this issue thread).

Perhaps this was a bit overly dramatic. But adding random line breaks (random in regard to the logic of the sentence) makes features like `orgrr-show-backlinks` or even resizing a window way more difficult.  

> 
> The backlinks indeed only adds the context up to the first 71st char line break. I think I can live with it. That's not awfully disruptive, imo. How would a proper backlinks contexts would look like? I imagine not much different than mine.

Depends on the length of the line. Usually more context is shown (if there is any).

![Bildschirmfoto 2024-12-21 um 13 12 58](https://github.com/user-attachments/assets/db169a8e-f988-4c7c-8013-d59e99df3dcc)

> 
> Perhaps, would you consider extending this addition of the context up to the next **dot and then double spaces?** This is how I put the sentence ending dot and the whitespaces.
> 
> OR, would you consider this addition of the backlinks context up to the next **double newline characters?** This is also how I separate my paragraphs (just as in here, markdown, or in the reddit, the user uses double newlines to separate paragraphs).

This is what I meant above. I would have to develop a complex logic just to check for the end of the paragraph and explain this in the documentation to everyone (and I'm not even sure this would work with `rg`) - whereas the current version uses the natural context of the line/paragraph in the original note (as identified by `rg`). In addition this is a feature I wouldn't ever use myself.

**Comment by k4r4b3y** [comment]
I can live with the backlinks buffer as I have it currently.  No sweat!  Thanks for reminding me of this, though.

**Comment by k4r4b3y** [comment]
`orgrr-add-to-project` works beautifully with the selected region now.  Thank you.
