### ISSUE TITLE
orgrr-find: You can search for any combination of tags, zettel ID and title (or alias)

### ISSUE THREAD

**Issue by rbenit68** [rtrppl/orgrr#7]
Nice package, thank you.

In readme.md you state about orgrr-find (and others) "You can search for any combination of tags, zettel ID and title (or alias)". Can you show the way to proceed interactively to find, for example, one or several tags?

Miguel.

**Comment by rtrppl** [comment]
Thanks, Miguel! 

Right now tags (and zettel-ids) are added to the title (and the alias) for completing-read. 

<img width="1356" alt="tags" src="https://github.com/rtrppl/orgrr/assets/63909884/ea49436c-48fd-4bf7-9c2b-396a20efaadb">

So the way to search for a notes with certain tags is pretty straight forward: you start typing those tags. I use tags only for a very limited subset of meta-data for primary and secondary sources. See below an example for the combination of "books" and "2024" (I add a tag for the year and month in which I read a publication).

<img width="1351" alt="book   2024" src="https://github.com/rtrppl/orgrr/assets/63909884/daa58221-f936-4e6c-9ffe-f4740c7a900d">
